version: '3'
services:
  uvirtual:
    image: uvirtual2021
    volumes:
      - ${MOODLE_FOLDER}:/var/www/html/moodle
      - ${MOODLEDATA_FOLDER}:/var/www/html/moodledata
      - ${MOODLE_LOG_FOLDER}:/var/log/httpd
      - ./.env:/home/.env
    command: bash /home/start.sh
    ports:
      - ${MOODLE_NETWORK}:${MOODLE_PORT}:80


